### ISSUE TITLE
[OSD-12116] Akeneo Sync Performance Degradation in STG

### ISSUE THREAD

**Issue by ochumkv** [creativestyle/OroAkeneoBundle#4]
Full Akeneo product sync started last night on job #75,653,581.  The sync initially performed as expected, but has since degraded to unacceptable speed.  Product batches typically execute in less than a minute.  About five hours after the sync started, product batches started to take 5 minutes to complete (job #75,656,770).

Company Huyett
Application version 4.2.17

cc @jkanclerz

**Comment by ochumkv** [comment]
Update on current Akeneo full product sync that was started last night at 9:41pm.

![image](https://github.com/creativestyle/OroAkeneoBundle/assets/96531254/b06815f9-afb0-47e2-8741-da0816795a6f)


Product batches (25 each) are now taking a little longer than yesterday evening.

![image](https://github.com/creativestyle/OroAkeneoBundle/assets/96531254/fb838e71-0281-4225-bf9d-a165a99d7579)


Looks like it’s 5 minutes per batch right now (when it started running, it was about 1 minute per batch).

**Comment by ochumkv** [comment]
close it please

**Comment by jkanclerz** [comment]
test infrastructure-related issue, closing
